export const initialProducts = [
  {
    id: 'ea9045dd-8e67-4456-9073-18856a8ac350',
    title: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    tags: ['TRADICIONAL'],
    price: 9.9,
    priceText: '9,90',
    imgUrl: 'expresso.svg',
  },
  {
    id: '2f447a93-0e7c-45ff-a10f-e93f591aec22',
    title: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    tags: ['TRADICIONAL'],
    price: 9.9,
    priceText: '9,90',
    imgUrl: 'americano.svg',
  },
  {
    id: '0f4bace9-75d8-451c-a569-bf1f0961fa8d',
    title: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    tags: ['TRADICIONAL'],
    price: 9.9,
    priceText: '9,90',
    imgUrl: 'expresso-cremoso.svg',
  },
  {
    id: 'e5f92f75-d045-45aa-a824-9cadcd3dd2b3',
    title: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    tags: ['TRADICIONAL', 'GELADO'],
    price: 9.9,
    priceText: '9,90',
    imgUrl: 'cafe-gelado.svg',
  },
  {
    id: '5a778925-9a0f-4135-91d1-086f3668175c',
    title: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    tags: ['TRADICIONAL', 'COM LEITE'],
    price: 9.9,
    priceText: '9,90',
    imgUrl: 'cafe-com-leite.svg',
  },
  {
    id: '6d308530-b759-40c3-99b6-dd3995ea6307',
    title: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    tags: ['TRADICIONAL', 'COM LEITE'],
    price: 9.9,
    priceText: '9,90',
    imgUrl: 'latte.svg',
  },
  {
    id: 'd9d95af1-4354-40ef-913e-a75a6053c88e',
    title: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    tags: ['TRADICIONAL', 'COM LEITE'],
    price: 9.9,
    priceText: '9,90',
    imgUrl: 'capuccino.svg',
  },
  {
    id: '0f904de3-2548-405d-9fed-9dd562f9e93d',
    title: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    tags: ['TRADICIONAL', 'COM LEITE'],
    price: 9.9,
    priceText: '9,90',
    imgUrl: 'macchiato.svg',
  },
  {
    id: '19fd5dea-9d64-4b07-a8b5-89aec95abef5',
    title: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    tags: ['TRADICIONAL', 'COM LEITE'],
    price: 9.9,
    priceText: '9,90',
    imgUrl: 'mocaccino.svg',
  },
  {
    id: '0e9ffea6-3010-4e75-8f76-4493641e3436',
    title: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    tags: ['ESPECIAL', 'COM LEITE'],
    price: 9.9,
    priceText: '9,90',
    imgUrl: 'chocolate-quente.svg',
  },
  {
    id: '6236332e-c9cc-4061-8523-95aacc968258',
    title: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    tags: ['ESPECIAL', 'ALCOÓLICO', 'GELADO'],
    price: 9.9,
    priceText: '9,90',
    imgUrl: 'cubano.svg',
  },
  {
    id: '4fcdeaaf-10f4-48c3-abfd-644a2a7bb2ed',
    title: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    tags: ['ESPECIAL'],
    price: 9.9,
    priceText: '9,90',
    imgUrl: 'havaiano.svg',
  },
  {
    id: '5003c2c6-de9c-45b3-9fc3-938b2608d484',
    title: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    tags: ['ESPECIAL'],
    price: 9.9,
    priceText: '9,90',
    imgUrl: 'arabe.svg',
  },
  {
    id: 'eebb1840-5c62-49e9-bd0f-f4c5b6e96d9a',
    title: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    tags: ['ESPECIAL', 'ALCOÓLICO'],
    price: 9.9,
    priceText: '9,90',
    imgUrl: 'irlandes.svg',
  },
]
